### ISSUE TITLE
[pkgs] Execution Path + Remappings Fix = Compilers Orchestration Through CLI

### ISSUE THREAD

**Issue by VoR0220** [monax/monax#1166]
This is a consolidation of previous issues that are all related and will be taken out in sync in a roadmap format. The overall goal is to create a better PM jobs experience and to enable full remapping utilization as well as multi compiler utilization. The problems for each of these issues will be listed below. 

- [ ] (Previously held at #904 ) Solidifying Path Execution Rules
Problem: We don't have good, clear rules for execution. There's too much going on that confuses EPM in finding yaml files, contract-path, the project root, and the abi path whenever `eris pkgs do` is executed. This leads to the problems in the above issue. There's simply too much going on here. We need to narrow this down and become more opinionated. 

Solution:
Define project root as the point of where `eris pkgs do` is executed, aka the `pwd`. If the yamlPath is not specified, then it is assumed that there is a `epm.yaml` file in the `pwd` and an error will be thrown if one is not there. Furthermore, `contract-path` will be deprecated, and contracts will execute relative to the point of where the `epm.yaml` is. Abi path which is already scheduled for deprecation will be deprecated and the `./abi` folder will simply be found in the `pwd`. 
- [ ] (Previously held at #1128) Remappings implementation in Compilers
Due to the path execution rules, we can't implement an easy fix here, so this relies on the above to be fixed first.
Problem: The current way the compilers service works is that client side it implements a recursive hashing/replacement in file algorithm to find all dependencies of a solidity file. These dependencies are then bundled together and executed in one single directory. This was made during a time when Solidity did not have path remappings and is no longer useful and is actually hindering us at the moment. 

Solution: Copy entire project root directory into the container. Execute solc commands from there. At the beginning there will be a global default remapping for the contract_bundles directory. Unsure whether to take it further than that for the time being. 
- [ ] (Previously held at #1164 ) 
Due to the previous two problems, and time constraints, this will be the last to be worked on but it is essential for package management.
Problems: The compilers service is no longer necessary with the advent of automated docker deployments coming about. Currently the compilers service only enables one version of Solidity to be worked with at a time. The package manager requires the ability to access and grab multiple versions of solidity. 

Solution: Rather what we should be shifting to is a CLI orchestrated array of compiler images and having the CLI coordinate between the project/package manager and the images.

**Comment by VoR0220** [comment]
@j-h-scheufen please review and make sure you agree with the above. I begin unit testing for this #1 tonight.

**Comment by j-h-scheufen** [comment]
@VoR0220 One comment is important here! Let's go for the small but important wins. Orchestration of multiple compiler version (#1164) is NOT a requirement for us at the moment and not a requirement to get to a working package manager. It's perfectly fine to assume that dependencies are either already compiled and binary or are compatible with a compiler version supported by the CLI release. Let's move this out of scope for now, please!

**Comment by j-h-scheufen** [comment]
@VoR0220 As part of the solution to #1128, let's also please cover the problem of the entire directory being copies OUT OF the compilers container after running the jobs, just in order to get the ABI folder out. I don't find the ticket right now, this was an existing ticket by @compleatang AFAIR from the beginning of 2016! It fits perfectly into the changes of #1128.

**Comment by VoR0220** [comment]
@j-h-scheufen The orchestration of compiler versions is already done. Like literally, I'm finished making it. Also the second one is already done, that's no problem. Literally, am finished with those parts.

**Comment by zramsay** [comment]
how much of this is addressed by #1323 or captured in other issues?

**Comment by VoR0220** [comment]
All except for maybe the last one, everything else is addressed

**Comment by VoR0220** [comment]
The problem is solved in 1323 but it's not the full on list of compilers and orchestration through CLI point yet. But it gets the bare bones in there.

**Comment by zramsay** [comment]
replacing with specific issues
